/* CVS $Id: $ */
package org.vivoweb.harvester.extractdspace.vocab.dspace;
import org.apache.jena.rdf.model.*;
import org.apache.jena.ontology.*;
 
/**
 * Vocabulary definitions from /home/heon/01-SPRINT/00-PROJET-DSPACE-VIVO/00-GIT/DSpace-VIVO/bundles/org.vivoweb.dspacevivo.model.ontologie/src/main/resources/dspace.ttl 
 * @author Auto-generated by schemagen on 30 mars 2022 06:34 
 */
public class DSPACE {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static final OntModel M_MODEL = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://vivoweb.org/ontology/dspace#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     * @return namespace as String
     * @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = M_MODEL.createResource( NS );
    
    /** <p>The ontology's owl:versionInfo as a string</p> */
    public static final String VERSION_INFO = "Created by Michel Héon PhD; Université du Québec à Montréal; heon.michel@uqam.ca";
    
    public static final ObjectProperty hasCollection = M_MODEL.createObjectProperty( "http://vivoweb.org/ontology/dspace#hasCollection" );
    
    public static final ObjectProperty hasCommunity = M_MODEL.createObjectProperty( "http://vivoweb.org/ontology/dspace#hasCommunity" );
    
    public static final ObjectProperty hasItem = M_MODEL.createObjectProperty( "http://vivoweb.org/ontology/dspace#hasItem" );
    
    public static final ObjectProperty isPartOfCollection = M_MODEL.createObjectProperty( "http://vivoweb.org/ontology/dspace#isPartOfCollection" );
    
    public static final ObjectProperty isPartOfCommunity = M_MODEL.createObjectProperty( "http://vivoweb.org/ontology/dspace#isPartOfCommunity" );
    
    public static final ObjectProperty isPartOfRepository = M_MODEL.createObjectProperty( "http://vivoweb.org/ontology/dspace#isPartOfRepository" );
    
    public static final DatatypeProperty hasBitstream = M_MODEL.createDatatypeProperty( "http://vivoweb.org/ontology/dspace#hasBitstream" );
    
    public static final OntClass Collection = M_MODEL.createClass( "http://vivoweb.org/ontology/dspace#Collection" );
    
    public static final OntClass Community = M_MODEL.createClass( "http://vivoweb.org/ontology/dspace#Community" );
    
    public static final OntClass Item = M_MODEL.createClass( "http://vivoweb.org/ontology/dspace#Item" );
    
    public static final OntClass Repository = M_MODEL.createClass( "http://vivoweb.org/ontology/dspace#Repository" );
    
}
