/*
 * DSpace-VIVO EXchange Data Schema (DVExDS)
 * This is the \"DSpace-VIVO EXchange Data Schema (DVExDS)\" based on the OpenAPI 3.0.2 specification. You can find out more about Swagger at [http://swagger.io](http://swagger.io). In the third iteration of the pet store, we've switched to the design first approach! You can now help us improve the API whether it's by making changes to the definition itself or to the code. That way, with time, we can improve the API in general, and expose some of the new features in OAS3. Some useful links: - [DSpace-VIVO - Integration project of DSpace metadata with VIVO](https://github.com/vivo-community/DSpace-VIVO)  - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore) - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
 *
 * OpenAPI spec version: 1.1.0
 * Contact: vivo@uqam.ca
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.vivoweb.dspacevivo.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import org.vivoweb.dspacevivo.model.Collection;
import org.vivoweb.dspacevivo.model.Community;
import org.vivoweb.dspacevivo.model.Statement;
import org.vivoweb.dspacevivo.model.StatementLiteral;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * Community
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2024-11-21T11:34:55.324490+01:00[Europe/Belgrade]")public class Community   {
  @JsonProperty("dspaceType")
  private String dspaceType = "community";

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("uri")
  private String uri = null;

  @JsonProperty("url")
  private String url = null;

  @JsonProperty("hasCollection")
  private List<Collection> hasCollection = null;

  @JsonProperty("hasSubCommunity")
  private List<Community> hasSubCommunity = null;

  @JsonProperty("isSubcommunityOfID")
  private List<String> isSubcommunityOfID = null;

  @JsonProperty("isPartOfRepositoryID")
  private List<String> isPartOfRepositoryID = null;

  @JsonProperty("listOfStatements")
  private List<Statement> listOfStatements = null;

  @JsonProperty("listOfStatementLiterals")
  private List<StatementLiteral> listOfStatementLiterals = null;

  /**
   * Get dspaceType
   * @return dspaceType
   **/
  @JsonProperty("dspaceType")
  @Schema(description = "")
  public String getDspaceType() {
    return dspaceType;
  }

  public Community id(String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   **/
  @JsonProperty("id")
  @Schema(example = "123456789/1", required = true, description = "")
  @NotNull
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Community uri(String uri) {
    this.uri = uri;
    return this;
  }

  /**
   * Get uri
   * @return uri
   **/
  @JsonProperty("uri")
  @Schema(example = "http://localhost:4000/handle/123456789/1", required = true, description = "")
  @NotNull
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }

  public Community url(String url) {
    this.url = url;
    return this;
  }

  /**
   * Get url
   * @return url
   **/
  @JsonProperty("url")
  @Schema(example = "http://localhost:4000/communities/b278a9dd-9c63-4864-9c6e-0a6caa8ff459", required = true, description = "")
  @NotNull
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public Community hasCollection(List<Collection> hasCollection) {
    this.hasCollection = hasCollection;
    return this;
  }

  public Community addHasCollectionItem(Collection hasCollectionItem) {
    if (this.hasCollection == null) {
      this.hasCollection = new ArrayList<>();
    }
    this.hasCollection.add(hasCollectionItem);
    return this;
  }

  /**
   * Get hasCollection
   * @return hasCollection
   **/
  @JsonProperty("hasCollection")
  @Schema(example = "1234567892", description = "")
  @Valid
  public List<Collection> getHasCollection() {
    return hasCollection;
  }

  public void setHasCollection(List<Collection> hasCollection) {
    this.hasCollection = hasCollection;
  }

  public Community hasSubCommunity(List<Community> hasSubCommunity) {
    this.hasSubCommunity = hasSubCommunity;
    return this;
  }

  public Community addHasSubCommunityItem(Community hasSubCommunityItem) {
    if (this.hasSubCommunity == null) {
      this.hasSubCommunity = new ArrayList<>();
    }
    this.hasSubCommunity.add(hasSubCommunityItem);
    return this;
  }

  /**
   * Get hasSubCommunity
   * @return hasSubCommunity
   **/
  @JsonProperty("hasSubCommunity")
  @Schema(description = "")
  @Valid
  public List<Community> getHasSubCommunity() {
    return hasSubCommunity;
  }

  public void setHasSubCommunity(List<Community> hasSubCommunity) {
    this.hasSubCommunity = hasSubCommunity;
  }

  public Community isSubcommunityOfID(List<String> isSubcommunityOfID) {
    this.isSubcommunityOfID = isSubcommunityOfID;
    return this;
  }

  public Community addIsSubcommunityOfIDItem(String isSubcommunityOfIDItem) {
    if (this.isSubcommunityOfID == null) {
      this.isSubcommunityOfID = new ArrayList<>();
    }
    this.isSubcommunityOfID.add(isSubcommunityOfIDItem);
    return this;
  }

  /**
   * Get isSubcommunityOfID
   * @return isSubcommunityOfID
   **/
  @JsonProperty("isSubcommunityOfID")
  @Schema(description = "")
  public List<String> getIsSubcommunityOfID() {
    return isSubcommunityOfID;
  }

  public void setIsSubcommunityOfID(List<String> isSubcommunityOfID) {
    this.isSubcommunityOfID = isSubcommunityOfID;
  }

  public Community isPartOfRepositoryID(List<String> isPartOfRepositoryID) {
    this.isPartOfRepositoryID = isPartOfRepositoryID;
    return this;
  }

  public Community addIsPartOfRepositoryIDItem(String isPartOfRepositoryIDItem) {
    if (this.isPartOfRepositoryID == null) {
      this.isPartOfRepositoryID = new ArrayList<>();
    }
    this.isPartOfRepositoryID.add(isPartOfRepositoryIDItem);
    return this;
  }

  /**
   * Get isPartOfRepositoryID
   * @return isPartOfRepositoryID
   **/
  @JsonProperty("isPartOfRepositoryID")
  @Schema(description = "")
  public List<String> getIsPartOfRepositoryID() {
    return isPartOfRepositoryID;
  }

  public void setIsPartOfRepositoryID(List<String> isPartOfRepositoryID) {
    this.isPartOfRepositoryID = isPartOfRepositoryID;
  }

  public Community listOfStatements(List<Statement> listOfStatements) {
    this.listOfStatements = listOfStatements;
    return this;
  }

  public Community addListOfStatementsItem(Statement listOfStatementsItem) {
    if (this.listOfStatements == null) {
      this.listOfStatements = new ArrayList<>();
    }
    this.listOfStatements.add(listOfStatementsItem);
    return this;
  }

  /**
   * Get listOfStatements
   * @return listOfStatements
   **/
  @JsonProperty("listOfStatements")
  @Schema(description = "")
  @Valid
  public List<Statement> getListOfStatements() {
    return listOfStatements;
  }

  public void setListOfStatements(List<Statement> listOfStatements) {
    this.listOfStatements = listOfStatements;
  }

  public Community listOfStatementLiterals(List<StatementLiteral> listOfStatementLiterals) {
    this.listOfStatementLiterals = listOfStatementLiterals;
    return this;
  }

  public Community addListOfStatementLiteralsItem(StatementLiteral listOfStatementLiteralsItem) {
    if (this.listOfStatementLiterals == null) {
      this.listOfStatementLiterals = new ArrayList<>();
    }
    this.listOfStatementLiterals.add(listOfStatementLiteralsItem);
    return this;
  }

  /**
   * Get listOfStatementLiterals
   * @return listOfStatementLiterals
   **/
  @JsonProperty("listOfStatementLiterals")
  @Schema(description = "")
  @Valid
  public List<StatementLiteral> getListOfStatementLiterals() {
    return listOfStatementLiterals;
  }

  public void setListOfStatementLiterals(List<StatementLiteral> listOfStatementLiterals) {
    this.listOfStatementLiterals = listOfStatementLiterals;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Community community = (Community) o;
    return Objects.equals(this.dspaceType, community.dspaceType) &&
        Objects.equals(this.id, community.id) &&
        Objects.equals(this.uri, community.uri) &&
        Objects.equals(this.url, community.url) &&
        Objects.equals(this.hasCollection, community.hasCollection) &&
        Objects.equals(this.hasSubCommunity, community.hasSubCommunity) &&
        Objects.equals(this.isSubcommunityOfID, community.isSubcommunityOfID) &&
        Objects.equals(this.isPartOfRepositoryID, community.isPartOfRepositoryID) &&
        Objects.equals(this.listOfStatements, community.listOfStatements) &&
        Objects.equals(this.listOfStatementLiterals, community.listOfStatementLiterals);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dspaceType, id, uri, url, hasCollection, hasSubCommunity, isSubcommunityOfID, isPartOfRepositoryID, listOfStatements, listOfStatementLiterals);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Community {\n");
    
    sb.append("    dspaceType: ").append(toIndentedString(dspaceType)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    hasCollection: ").append(toIndentedString(hasCollection)).append("\n");
    sb.append("    hasSubCommunity: ").append(toIndentedString(hasSubCommunity)).append("\n");
    sb.append("    isSubcommunityOfID: ").append(toIndentedString(isSubcommunityOfID)).append("\n");
    sb.append("    isPartOfRepositoryID: ").append(toIndentedString(isPartOfRepositoryID)).append("\n");
    sb.append("    listOfStatements: ").append(toIndentedString(listOfStatements)).append("\n");
    sb.append("    listOfStatementLiterals: ").append(toIndentedString(listOfStatementLiterals)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
