/* CVS $Id: $ */
package org.vivoweb.harvester.extractdspace.vocab.vitro;
import org.apache.jena.rdf.model.*;
import org.apache.jena.ontology.*;
 
/**
 * Vocabulary definitions from /home/heon/01-SPRINT/00-PROJET-DSPACE-VIVO/00-GIT/DSpace-VIVO/bundles/org.vivoweb.dspacevivo.model.ontologie/src/main/resources/vitro-0.7.ttl 
 * @author Auto-generated by schemagen on 30 mars 2022 06:31 
 */
public class VITRO {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static final OntModel M_MODEL = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     * @return namespace as String
     * @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = M_MODEL.createResource( NS );
    
    /** <p>The ontology's owl:versionInfo as a string</p> */
    public static final String VERSION_INFO = "0.7";
    
    public static final ObjectProperty rootTab = M_MODEL.createObjectProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#rootTab" );
    
    public static final DatatypeProperty aboutText = M_MODEL.createDatatypeProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#aboutText" );
    
    public static final DatatypeProperty acknowledgeText = M_MODEL.createDatatypeProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#acknowledgeText" );
    
    public static final DatatypeProperty bannerHeight = M_MODEL.createDatatypeProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#bannerHeight" );
    
    public static final DatatypeProperty bannerImage = M_MODEL.createDatatypeProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#bannerImage" );
    
    public static final DatatypeProperty bannerWidth = M_MODEL.createDatatypeProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#bannerWidth" );
    
    public static final DatatypeProperty contactMail = M_MODEL.createDatatypeProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#contactMail" );
    
    public static final DatatypeProperty copyrightAnchor = M_MODEL.createDatatypeProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#copyrightAnchor" );
    
    public static final DatatypeProperty copyrightURL = M_MODEL.createDatatypeProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#copyrightURL" );
    
    public static final DatatypeProperty displayLimit = M_MODEL.createDatatypeProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#displayLimit" );
    
    public static final DatatypeProperty displayRank = M_MODEL.createDatatypeProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#displayRank" );
    
    public static final DatatypeProperty firstTime = M_MODEL.createDatatypeProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#firstTime" );
    
    public static final DatatypeProperty hidden = M_MODEL.createDatatypeProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#hidden" );
    
    public static final DatatypeProperty imageThumbWidth = M_MODEL.createDatatypeProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#imageThumbWidth" );
    
    public static final DatatypeProperty loginCount = M_MODEL.createDatatypeProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#loginCount" );
    
    public static final DatatypeProperty logotypeHeight = M_MODEL.createDatatypeProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#logotypeHeight" );
    
    public static final DatatypeProperty logotypeImage = M_MODEL.createDatatypeProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#logotypeImage" );
    
    public static final DatatypeProperty logotypeWidth = M_MODEL.createDatatypeProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#logotypeWidth" );
    
    public static final DatatypeProperty md5password = M_MODEL.createDatatypeProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#md5password" );
    
    public static final DatatypeProperty modTime = M_MODEL.createDatatypeProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#modTime" );
    
    public static final DatatypeProperty moniker = M_MODEL.createDatatypeProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#moniker" );
    
    public static final DatatypeProperty namespaceURI = M_MODEL.createDatatypeProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#namespaceURI" );
    
    public static final DatatypeProperty oldpassword = M_MODEL.createDatatypeProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#oldpassword" );
    
    public static final DatatypeProperty roleURI = M_MODEL.createDatatypeProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#roleURI" );
    
    public static final DatatypeProperty rootBreadCrumbAnchor = M_MODEL.createDatatypeProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#rootBreadCrumbAnchor" );
    
    public static final DatatypeProperty rootBreadCrumbURL = M_MODEL.createDatatypeProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#rootBreadCrumbURL" );
    
    public static final DatatypeProperty rootLogotypeImage = M_MODEL.createDatatypeProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#rootLogotypeImage" );
    
    public static final DatatypeProperty shortHand = M_MODEL.createDatatypeProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#shortHand" );
    
    public static final DatatypeProperty themeDir = M_MODEL.createDatatypeProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#themeDir" );
    
    public static final DatatypeProperty urlPrefix = M_MODEL.createDatatypeProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#urlPrefix" );
    
    public static final DatatypeProperty username = M_MODEL.createDatatypeProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#username" );
    
    public static final AnnotationProperty customDisplayViewAnnot = M_MODEL.createAnnotationProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#customDisplayViewAnnot" );
    
    public static final AnnotationProperty customEntryFormAnnot = M_MODEL.createAnnotationProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#customEntryFormAnnot" );
    
    public static final AnnotationProperty customShortViewAnnot = M_MODEL.createAnnotationProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#customShortViewAnnot" );
    
    public static final AnnotationProperty descriptionAnnot = M_MODEL.createAnnotationProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#descriptionAnnot" );
    
    public static final AnnotationProperty displayLimitAnnot = M_MODEL.createAnnotationProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#displayLimitAnnot" );
    
    public static final AnnotationProperty displayRankAnnot = M_MODEL.createAnnotationProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#displayRankAnnot" );
    
    public static final AnnotationProperty editing = M_MODEL.createAnnotationProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#editing" );
    
    public static final AnnotationProperty exampleAnnot = M_MODEL.createAnnotationProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#exampleAnnot" );
    
    public static final AnnotationProperty extendedLinkedData = M_MODEL.createAnnotationProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#extendedLinkedData" );
    
    public static final AnnotationProperty forceStubDeletionAnnot = M_MODEL.createAnnotationProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#forceStubDeletionAnnot" );
    
    public static final AnnotationProperty fullPropertyNameAnnot = M_MODEL.createAnnotationProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#fullPropertyNameAnnot" );
    
    public static final AnnotationProperty harvestId = M_MODEL.createAnnotationProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#harvestId" );
    
    public static final AnnotationProperty hiddenAnnot = M_MODEL.createAnnotationProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#hiddenAnnot" );
    
    public static final AnnotationProperty hiddenFromDisplayBelowRoleLevelAnnot = M_MODEL.createAnnotationProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#hiddenFromDisplayBelowRoleLevelAnnot" );
    
    public static final AnnotationProperty hiddenFromPublishBelowRoleLevelAnnot = M_MODEL.createAnnotationProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#hiddenFromPublishBelowRoleLevelAnnot" );
    
    public static final AnnotationProperty inClassGroup = M_MODEL.createAnnotationProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#inClassGroup" );
    
    public static final AnnotationProperty inPropertyGroupAnnot = M_MODEL.createAnnotationProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#inPropertyGroupAnnot" );
    
    public static final AnnotationProperty individualSortDirectionAnnot = M_MODEL.createAnnotationProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#individualSortDirectionAnnot" );
    
    public static final AnnotationProperty isExternalId = M_MODEL.createAnnotationProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#isExternalId" );
    
    public static final AnnotationProperty isMenuPageIntersectionClass = M_MODEL.createAnnotationProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#isMenuPageIntersectionClass" );
    
    public static final AnnotationProperty modTimeAnnot = M_MODEL.createAnnotationProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#modTimeAnnot" );
    
    public static final AnnotationProperty mostSpecificType = M_MODEL.createAnnotationProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType" );
    
    public static final AnnotationProperty objectIndividualSortProperty = M_MODEL.createAnnotationProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#objectIndividualSortProperty" );
    
    public static final AnnotationProperty offerCreateNewOptionAnnot = M_MODEL.createAnnotationProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#offerCreateNewOptionAnnot" );
    
    public static final AnnotationProperty oldId = M_MODEL.createAnnotationProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#oldId" );
    
    public static final AnnotationProperty originalId = M_MODEL.createAnnotationProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#originalId" );
    
    public static final AnnotationProperty prohibitedFromUpdateBelowRoleLevelAnnot = M_MODEL.createAnnotationProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#prohibitedFromUpdateBelowRoleLevelAnnot" );
    
    public static final AnnotationProperty publicDescriptionAnnot = M_MODEL.createAnnotationProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#publicDescriptionAnnot" );
    
    public static final AnnotationProperty selectFromExistingAnnot = M_MODEL.createAnnotationProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#selectFromExistingAnnot" );
    
    public static final AnnotationProperty shortDef = M_MODEL.createAnnotationProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#shortDef" );
    
    public static final AnnotationProperty shortDefAnnot = M_MODEL.createAnnotationProperty( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#shortDefAnnot" );
    
    public static final OntClass Application = M_MODEL.createClass( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#Application" );
    
    public static final OntClass ClassGroup = M_MODEL.createClass( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#ClassGroup" );
    
    public static final OntClass Namespace = M_MODEL.createClass( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#Namespace" );
    
    public static final OntClass Portal = M_MODEL.createClass( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#Portal" );
    
    public static final OntClass PropertyGroup = M_MODEL.createClass( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#PropertyGroup" );
    
    public static final OntClass User = M_MODEL.createClass( "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#User" );
    
}
